set(sources
		main.cpp
		MainWindow.cpp
		ToolBar.cpp
		ApplicationSettings.cpp
		WorkSpace.cpp
		GraphicsRectangle.cpp
		GraphicsScene.cpp
		ImageLayer.cpp
		LayerPreview.cpp
		NewCanvasDialog.cpp
		ToolBarButton.cpp
		Canvas.cpp
		ColorPicker.cpp
		RectangleSelectionTool.cpp
		ScaleTool.cpp
		RotationTool.cpp
		TextTool.cpp
		TextEditOptions.cpp
		TextAreaTool.cpp
		ChangeCanvasSizeDialog.cpp
		NewLayerDialog.cpp
		GaussianBlur.cpp
		)

set(headers
		MainWindow.h
		ToolBar.h
		ApplicationSettings.h
		WorkSpace.h
		GraphicsRectangle.h
		GraphicsScene.h
		ImageLayer.h
		LayerPreview.h
		NewCanvasDialog.h
		ToolBarButton.h
		Canvas.h
		Globals.h
		ColorPicker.h
		RectangleSelectionTool.h
		ScaleTool.h
		RotationTool.h
		TextTool.h
		TextEditOptions.h
		TextAreaTool.h
		ChangeCanvasSizeDialog.h
		NewLayerDialog.h
		GaussianBlur.h
		)