set(sources
		main.cpp
		MainWindow.cpp
		ToolBar.cpp
		ApplicationSettings.cpp
		WorkSpace.cpp
		GraphicsRectangle.cpp
		GraphicsScene.cpp
		ImageLayer.cpp
		LayerPreview.cpp
		NewCanvasDialog.cpp
		ToolBarButton.cpp
		Canvas.cpp
		ColorPicker.cpp
		RectangleSelectionTool.cpp
		)

set(headers
		MainWindow.h
		ToolBar.h
		ApplicationSettings.h
		WorkSpace.h
		GraphicsRectangle.h
		GraphicsScene.h
		ImageLayer.h
		LayerPreview.h
		NewCanvasDialog.h
		ToolBarButton.h
		Canvas.h
		Globals.h
		ColorPicker.h
		RectangleSelectionTool.h
		)