set(sources
		main.cpp
		MainWindow.cpp
		ToolBar.cpp
		ApplicationSettings.cpp
		WorkSpace.cpp
		GraphicsRectangle.cpp
		GraphicsScene.cpp
		ImageLayer.cpp
		LayerPreview.cpp
		NewCanvasDialog.cpp
		ToolBarButton.cpp
		Canvas.cpp
		LayersView.cpp
		LayerSystem/Model.cpp
		LayerSystem/Controller.cpp
		LayerSystem/LayerSystemMain.cpp
		LayerSystem/View.cpp
		)

set(headers
		MainWindow.h
		ToolBar.h
		ApplicationSettings.h
		WorkSpace.h
		GraphicsRectangle.h
		GraphicsScene.h
		ImageLayer.h
		LayerPreview.h
		NewCanvasDialog.h
		ToolBarButton.h
		Canvas.h
		Globals.h
		LayersView.h
		LayerSystem/Model.h
		LayerSystem/Controller.h
		LayerSystem/LayerSystemMain.h
		LayerSystem/View.h
		)